# tests/golden/test_projection_consistency.py
"""
Golden Reference Tests for LEACE Projection Consistency.

These tests validate:
1. LEACE idempotence property (P^2 ≈ P)
2. Cross-mode projection equivalence (laptop vs HPC)
3. Deterministic artifact generation on rerun

Golden fixtures are generated by scripts/generate_golden_fixtures.py
and stored in tests/golden/fixtures/
"""

import pytest
import torch
from pathlib import Path
from typing import Optional

from neuro_stylometry.pollution_guard.leace import LEACEComputer


# ==============================================================================
# Fixtures
# ==============================================================================

@pytest.fixture
def golden_fixtures_dir():
    """Return path to golden test fixtures directory."""
    return Path(__file__).parent / "fixtures"


@pytest.fixture
def golden_P_laptop(golden_fixtures_dir) -> Optional[torch.Tensor]:
    """Load golden laptop projection matrix."""
    path = golden_fixtures_dir / "expected_P_laptop_seed42.pt"
    if not path.exists():
        pytest.skip(f"Golden laptop projection not found: {path}")
    return torch.load(path, map_location="cpu")


@pytest.fixture
def golden_P_hpc(golden_fixtures_dir) -> Optional[torch.Tensor]:
    """Load golden HPC projection matrix."""
    path = golden_fixtures_dir / "expected_P_hpc_seed42.pt"
    if not path.exists():
        pytest.skip(f"Golden HPC projection not found: {path}")
    return torch.load(path, map_location="cpu")


@pytest.fixture
def golden_dataset_path(golden_fixtures_dir) -> Path:
    """Return path to golden dataset."""
    path = golden_fixtures_dir / "sobr_small_seed42.arrow"
    if not path.exists():
        pytest.skip(f"Golden dataset not found: {path}")
    return path


# ==============================================================================
# Idempotence Tests
# ==============================================================================

@pytest.mark.golden
@pytest.mark.determinism
class TestLEACEIdempotence:
    """Test LEACE projection idempotence property: P^2 ≈ P."""
    
    def test_leace_idempotence_golden_laptop(self, golden_P_laptop):
        """P^2 ≈ P for golden reference laptop projection matrix."""
        P = golden_P_laptop
        P2 = P @ P
        
        # Compute relative Frobenius error
        rel_error = torch.norm(P2 - P) / torch.norm(P)
        
        assert rel_error < 1e-5, (
            f"Idempotence violated for laptop projection: "
            f"||P^2 - P||_F / ||P||_F = {rel_error:.2e}"
        )
    
    def test_leace_idempotence_golden_hpc(self, golden_P_hpc):
        """P^2 ≈ P for golden reference HPC projection matrix."""
        P = golden_P_hpc
        P2 = P @ P
        
        # Compute relative Frobenius error
        rel_error = torch.norm(P2 - P) / torch.norm(P)
        
        assert rel_error < 1e-5, (
            f"Idempotence violated for HPC projection: "
            f"||P^2 - P||_F / ||P||_F = {rel_error:.2e}"
        )
    
    def test_leace_idempotence_synthetic(self, device):
        """P^2 ≈ P for freshly computed projection on synthetic data."""
        # Generate synthetic embeddings and labels
        torch.manual_seed(42)
        embeddings = torch.randn(500, 768, device=device)
        labels = torch.randint(0, 7, (500,), device=device)
        
        # Compute projection
        computer = LEACEComputer(
            embedding_dim=768, 
            device=str(device),
            force_cpu=(device == "cpu"),
        )
        P = computer.compute_projection(embeddings, labels)
        
        # Check idempotence
        P2 = P @ P
        rel_error = torch.norm(P2 - P) / torch.norm(P)
        
        assert rel_error < 1e-5, (
            f"Idempotence failed on synthetic data: "
            f"||P^2 - P||_F / ||P||_F = {rel_error:.2e}"
        )


# ==============================================================================
# Cross-Mode Equivalence Tests
# ==============================================================================

@pytest.mark.golden
@pytest.mark.determinism
class TestCrossModeEquivalence:
    """Test equivalence between laptop and HPC projection matrices."""
    
    def test_cross_mode_projection_correlation(self, golden_P_laptop, golden_P_hpc):
        """Laptop and HPC projections correlate > 0.98."""
        # Flatten to vectors for correlation
        p_laptop_vec = golden_P_laptop.flatten().float()
        p_hpc_vec = golden_P_hpc.flatten().float()
        
        # Pearson correlation
        stacked = torch.stack([p_laptop_vec, p_hpc_vec])
        correlation = torch.corrcoef(stacked)[0, 1]
        
        assert correlation > 0.98, (
            f"Cross-mode correlation too low: {correlation:.4f} (expected > 0.98)"
        )
    
    def test_cross_mode_projection_frobenius_error(self, golden_P_laptop, golden_P_hpc):
        """Laptop and HPC projections have < 5% Frobenius relative error."""
        P_laptop = golden_P_laptop.float()
        P_hpc = golden_P_hpc.float()
        
        # Frobenius relative error
        rel_error = torch.norm(P_laptop - P_hpc) / torch.norm(P_laptop)
        
        assert rel_error < 0.05, (
            f"Cross-mode Frobenius error too high: {rel_error:.4f} (expected < 0.05)"
        )
    
    def test_cross_mode_projection_shape(self, golden_P_laptop, golden_P_hpc):
        """Laptop and HPC projection matrices have same shape."""
        assert golden_P_laptop.shape == golden_P_hpc.shape, (
            f"Shape mismatch: laptop={golden_P_laptop.shape}, hpc={golden_P_hpc.shape}"
        )


# ==============================================================================
# Deterministic Rerun Tests
# ==============================================================================

@pytest.mark.golden
@pytest.mark.determinism
@pytest.mark.slow
class TestDeterministicRerun:
    """Test that Phase A produces identical artifacts on rerun."""
    
    def test_deterministic_rerun_artifact_identity(
        self, 
        golden_dataset_path, 
        tmp_path,
        set_all_seeds,
        laptop_strategy_with_config,
    ):
        """Running Phase A twice with seed=42 produces identical artifacts."""
        from neuro_stylometry.phase_a_pipeline import PhaseAPipeline
        
        strategy, config = laptop_strategy_with_config
        config["seed"] = 42
        
        # Run 1
        set_all_seeds(42)
        output_dir_1 = tmp_path / "run1"
        output_dir_1.mkdir()
        
        pipeline_1 = PhaseAPipeline(strategy=strategy, config=config)
        artifacts_1 = pipeline_1.run(golden_dataset_path, output_dir_1)
        
        # Run 2
        set_all_seeds(42)
        output_dir_2 = tmp_path / "run2"
        output_dir_2.mkdir()
        
        pipeline_2 = PhaseAPipeline(strategy=strategy, config=config)
        artifacts_2 = pipeline_2.run(golden_dataset_path, output_dir_2)
        
        # Assert projection matrix numerical equivalence
        P1 = torch.load(artifacts_1.projection_matrix_path, map_location="cpu")
        P2 = torch.load(artifacts_2.projection_matrix_path, map_location="cpu")
        
        assert torch.allclose(P1, P2, atol=1e-7), (
            "Projection matrices differ between runs. "
            f"Max diff: {torch.max(torch.abs(P1 - P2)):.2e}"
        )
        
        # Assert pollution logs have same count
        import pyarrow.feather as feather
        logs_1 = feather.read_table(artifacts_1.pollution_logs_path)
        logs_2 = feather.read_table(artifacts_2.pollution_logs_path)
        
        assert len(logs_1) == len(logs_2), (
            f"Pollution log count differs: {len(logs_1)} vs {len(logs_2)}"
        )


# ==============================================================================
# Projection Matrix Property Tests
# ==============================================================================

@pytest.mark.golden
class TestProjectionMatrixProperties:
    """Test mathematical properties of projection matrices."""
    
    def test_projection_matrix_shape(self, golden_P_laptop):
        """Projection matrix has expected shape (768, 768)."""
        assert golden_P_laptop.shape == (768, 768), (
            f"Expected shape (768, 768), got {golden_P_laptop.shape}"
        )
    
    def test_projection_matrix_dtype(self, golden_P_laptop):
        """Projection matrix is stored as FP32."""
        assert golden_P_laptop.dtype == torch.float32, (
            f"Expected dtype float32, got {golden_P_laptop.dtype}"
        )
    
    def test_projection_matrix_finite(self, golden_P_laptop):
        """Projection matrix contains no NaN or Inf values."""
        assert torch.isfinite(golden_P_laptop).all(), (
            "Projection matrix contains non-finite values"
        )
    
    def test_projection_matrix_bounded(self, golden_P_laptop):
        """Projection matrix eigenvalues are in [0, 1] (projection property)."""
        # Compute eigenvalues
        eigenvalues = torch.linalg.eigvalsh(golden_P_laptop)
        
        # Check bounds (with tolerance for numerical errors)
        assert eigenvalues.min() >= -1e-5, (
            f"Eigenvalues below 0: min={eigenvalues.min():.6f}"
        )
        assert eigenvalues.max() <= 1.0 + 1e-5, (
            f"Eigenvalues above 1: max={eigenvalues.max():.6f}"
        )
